### ISSUE TITLE
Build-info link doesn’t work. Plugin creates invalid url.

### ISSUE THREAD

**Issue by lezuch** [jfrog/teamcity-artifactory-plugin#119]
We're using Artifactory 7.41.7
Artifactory Plugin (2.9.4) creates an invalid URL. 
After clicking on "Artifactory Build Info" I  have a blank page.
Creates link 
https://<ARTIFACTORY_URL>/artifactory/webapp/builds/Test3/3
Instead 
https://<ARTIFACTORY_URL>/ui/builds/Test3/3

I assume the problem is here
```
        StringBuilder artifactoryUrlBuilder = new StringBuilder().append(selectedServerUrl);
        if (!selectedServerUrl.endsWith("/")) {
            artifactoryUrlBuilder.append("/");
        }
        String artifactoryUrl = artifactoryUrlBuilder
                .append("webapp/builds/")
```

With Artifatory 6,  the "Artifactory Build Info" links work fine.

**Comment by yahavi** [comment]
@lezuch,
Thanks for reporting this issue!
TeamCity Artifactory plugin 1.9.5 is released. This version includes the fix for this issue.

The version will be available shortly in the Jetbrains marketplace. In the meanwhile, you can download the plugin manually using this [link](https://releases.jfrog.io/artifactory/oss-release-local/org/jfrog/teamcity/teamcity-artifactory-plugin/2.9.5/teamcity-artifactory-plugin-2.9.5.zip).

Feel free to upgrade - we'd appreciate your feedback on that.

**Comment by Nheverest** [comment]
Hello,
A quick comment to say the solution requires the `/artifactory` context to be present in Artifactory's URL. 
Which does not seem mandatory based on **[Artifactory as Root Application in Tomcat](https://www.jfrog.com/confluence/display/JFROG/What%27s+New%3A+Self-Hosted#What'sNew:SelfHosted-Prem-BreakingChanges)**.
