### ISSUE TITLE
In version 2.9.0 we're seeing an error Unrecognized field "slf"

### ISSUE THREAD

**Issue by twalker-illumina** [jfrog/teamcity-artifactory-plugin#93]
Describe the bug
Unexpected field exception

To Reproduce

Expected behavior
Handle the field or ignore it

Screenshots

Versions
TeamCity Artifactory plugin version: 2.9.0
TeamCity Enterprise 2020.2.4 (build 86063) running on CentOS Linux 7
Artifactory Version: 7.19.4

Additional context
For teamcity plugin version 2.9.0 and artifactory version 7.19.4 we now see the following: error:com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "slf" (class org.jfrog.build.client.ArtifactoryUploadResponse), not marked as ignorable (12 known properties: "checksums", "size", "repo", "downloadUri", "path", "statusLine", "created", "errors", "uri", "mimeType", "createdBy", "originalChecksums"])

This is from a maven build. In our testing we haven't seen it occur in other builds.  Could this be related to Jenkins artifactory plugin issue #499?

V/r,
Terry

**Comment by eyalbe4** [comment]
Thanks for reporting this issue, @twalker-illumina!
Will you be able to confirm that upgrading to version 3.9.1 of the TeamCity Plugin resolves this issue?

**Comment by twalker-illumina** [comment]
Hi, version 2.9.1 is missing the agent and server directory structure of v2.9.0 and won't upload to TeamCity.  Are there patch instructions that would go with it?

Best,
Terry

**Comment by eyalbe4** [comment]
@twalker-illumina - we're checking this right now...

**Comment by yahavi** [comment]
@twalker-illumina,
Thanks for reporting this issue!
The root cause of it is a mistake in the plugin's download URL. We're sorry for the inconvenience. 
The link updated in the [documentation](https://www.jfrog.com/confluence/display/JFROG/TeamCity+Artifactory+Plug-in#TeamCityArtifactoryPlug-in-InstallingthePlugin) and verified.

Here's the correct link for 2.9.1:
https://oss.jfrog.org/artifactory/oss-release-local/org/jfrog/teamcity/teamcity-artifactory-plugin/2.9.1/teamcity-artifactory-plugin-2.9.1.zip

We'd appreciate your feedback on that.

**Comment by twalker-illumina** [comment]
Hi @yahavi, our engineers are happy to report the issue is resolved with version 2.9.1.  Thank you for the quick turn-around.

**Comment by eyalbe4** [comment]
Thank you for confirming @twalker-illumina!
